var annotated_dup =
[
    [ "cphot", "namespacecphot.html", "namespacecphot" ],
    [ "cphot_licks", "namespacecphot__licks.html", "namespacecphot__licks" ],
    [ "internal", "namespaceinternal.html", "namespaceinternal" ],
    [ "pretty_print", "namespacepretty__print.html", "namespacepretty__print" ],
    [ "rapidcsv", "namespacerapidcsv.html", "namespacerapidcsv" ],
    [ "rapidxml", "namespacerapidxml.html", "namespacerapidxml" ],
    [ "votable", "namespacevotable.html", "namespacevotable" ],
    [ "ASCII", "struct_a_s_c_i_i.html", "struct_a_s_c_i_i" ],
    [ "AutoUTF", "struct_auto_u_t_f.html", "struct_auto_u_t_f" ],
    [ "AutoUTFInputStream", "class_auto_u_t_f_input_stream.html", "class_auto_u_t_f_input_stream" ],
    [ "AutoUTFOutputStream", "class_auto_u_t_f_output_stream.html", "class_auto_u_t_f_output_stream" ],
    [ "BaseReaderHandler", "struct_base_reader_handler.html", "struct_base_reader_handler" ],
    [ "BasicIStreamWrapper", "class_basic_i_stream_wrapper.html", "class_basic_i_stream_wrapper" ],
    [ "BasicOStreamWrapper", "class_basic_o_stream_wrapper.html", "class_basic_o_stream_wrapper" ],
    [ "CrtAllocator", "class_crt_allocator.html", "class_crt_allocator" ],
    [ "EncodedInputStream", "class_encoded_input_stream.html", "class_encoded_input_stream" ],
    [ "EncodedInputStream< UTF8<>, MemoryStream >", "class_encoded_input_stream_3_01_u_t_f8_3_4_00_01_memory_stream_01_4.html", "class_encoded_input_stream_3_01_u_t_f8_3_4_00_01_memory_stream_01_4" ],
    [ "EncodedOutputStream", "class_encoded_output_stream.html", "class_encoded_output_stream" ],
    [ "FileReadStream", "class_file_read_stream.html", "class_file_read_stream" ],
    [ "FileWriteStream", "class_file_write_stream.html", "class_file_write_stream" ],
    [ "GenericArray", "class_generic_array.html", "class_generic_array" ],
    [ "GenericDocument", "class_generic_document.html", "class_generic_document" ],
    [ "GenericInsituStringStream", "struct_generic_insitu_string_stream.html", "struct_generic_insitu_string_stream" ],
    [ "GenericMember", "struct_generic_member.html", "struct_generic_member" ],
    [ "GenericMemberIterator", "class_generic_member_iterator.html", "class_generic_member_iterator" ],
    [ "GenericMemoryBuffer", "struct_generic_memory_buffer.html", "struct_generic_memory_buffer" ],
    [ "GenericObject", "class_generic_object.html", "class_generic_object" ],
    [ "GenericPointer", "class_generic_pointer.html", "class_generic_pointer" ],
    [ "GenericReader", "class_generic_reader.html", "class_generic_reader" ],
    [ "GenericSchemaDocument", "class_generic_schema_document.html", "class_generic_schema_document" ],
    [ "GenericSchemaValidator", "class_generic_schema_validator.html", "class_generic_schema_validator" ],
    [ "GenericStringBuffer", "class_generic_string_buffer.html", "class_generic_string_buffer" ],
    [ "GenericStringRef", "struct_generic_string_ref.html", "struct_generic_string_ref" ],
    [ "GenericStringStream", "struct_generic_string_stream.html", "struct_generic_string_stream" ],
    [ "GenericValue", "class_generic_value.html", "class_generic_value" ],
    [ "IGenericRemoteSchemaDocumentProvider", "class_i_generic_remote_schema_document_provider.html", "class_i_generic_remote_schema_document_provider" ],
    [ "imaxdiv_t", "structimaxdiv__t.html", "structimaxdiv__t" ],
    [ "MemoryPoolAllocator", "class_memory_pool_allocator.html", "class_memory_pool_allocator" ],
    [ "MemoryStream", "struct_memory_stream.html", "struct_memory_stream" ],
    [ "ParseResult", "struct_parse_result.html", "struct_parse_result" ],
    [ "PrettyWriter", "class_pretty_writer.html", "class_pretty_writer" ],
    [ "Allocator", "classrapidjson_1_1_allocator.html", null ],
    [ "Encoding", "classrapidjson_1_1_encoding.html", null ],
    [ "Handler", "classrapidjson_1_1_handler.html", null ],
    [ "Stream", "classrapidjson_1_1_stream.html", null ],
    [ "RQuantity", "class_r_quantity.html", "class_r_quantity" ],
    [ "SchemaValidatingReader", "class_schema_validating_reader.html", "class_schema_validating_reader" ],
    [ "StreamTraits", "struct_stream_traits.html", "struct_stream_traits" ],
    [ "StreamTraits< GenericInsituStringStream< Encoding > >", "struct_stream_traits_3_01_generic_insitu_string_stream_3_01_encoding_01_4_01_4.html", "struct_stream_traits_3_01_generic_insitu_string_stream_3_01_encoding_01_4_01_4" ],
    [ "StreamTraits< GenericStringStream< Encoding > >", "struct_stream_traits_3_01_generic_string_stream_3_01_encoding_01_4_01_4.html", "struct_stream_traits_3_01_generic_string_stream_3_01_encoding_01_4_01_4" ],
    [ "Transcoder", "struct_transcoder.html", "struct_transcoder" ],
    [ "Transcoder< Encoding, Encoding >", "struct_transcoder_3_01_encoding_00_01_encoding_01_4.html", "struct_transcoder_3_01_encoding_00_01_encoding_01_4" ],
    [ "UTF16", "struct_u_t_f16.html", "struct_u_t_f16" ],
    [ "UTF16BE", "struct_u_t_f16_b_e.html", "struct_u_t_f16_b_e" ],
    [ "UTF16LE", "struct_u_t_f16_l_e.html", "struct_u_t_f16_l_e" ],
    [ "UTF32", "struct_u_t_f32.html", "struct_u_t_f32" ],
    [ "UTF32BE", "struct_u_t_f32_b_e.html", "struct_u_t_f32_b_e" ],
    [ "UTF32LE", "struct_u_t_f32_l_e.html", "struct_u_t_f32_l_e" ],
    [ "UTF8", "struct_u_t_f8.html", "struct_u_t_f8" ],
    [ "Writer", "class_writer.html", "class_writer" ]
];