var hierarchy =
[
    [ "ASCII< CharType >", "struct_a_s_c_i_i.html", null ],
    [ "AutoUTF< CharType >", "struct_auto_u_t_f.html", null ],
    [ "AutoUTFInputStream< CharType, InputByteStream >", "class_auto_u_t_f_input_stream.html", null ],
    [ "AutoUTFOutputStream< CharType, OutputByteStream >", "class_auto_u_t_f_output_stream.html", null ],
    [ "BaseReaderHandler< Encoding, Derived >", "struct_base_reader_handler.html", null ],
    [ "BaseReaderHandler< typename SchemaDocumentType::SchemaType::EncodingType >", "struct_base_reader_handler.html", null ],
    [ "BasicIStreamWrapper< StreamType >", "class_basic_i_stream_wrapper.html", null ],
    [ "BasicOStreamWrapper< StreamType >", "class_basic_o_stream_wrapper.html", null ],
    [ "cphot::Filter", "classcphot_1_1_filter.html", null ],
    [ "cphot::filter_t", "structcphot_1_1filter__t.html", null ],
    [ "cphot::HDF5Library", "classcphot_1_1_h_d_f5_library.html", null ],
    [ "cphot::LickIndex", "classcphot_1_1_lick_index.html", null ],
    [ "cphot::LickLibrary", "classcphot_1_1_lick_library.html", null ],
    [ "cphot::Sun", "classcphot_1_1_sun.html", null ],
    [ "cphot::Vega", "classcphot_1_1_vega.html", null ],
    [ "cphot_licks::lickdata", "structcphot__licks_1_1lickdata.html", null ],
    [ "CrtAllocator", "class_crt_allocator.html", null ],
    [ "pretty_print::delimiters_values< char >", "structpretty__print_1_1delimiters__values.html", null ],
    [ "pretty_print::delimiters_values< wchar_t >", "structpretty__print_1_1delimiters__values.html", null ],
    [ "EncodedInputStream< Encoding, InputByteStream >", "class_encoded_input_stream.html", null ],
    [ "EncodedInputStream< UTF8<>, MemoryStream >", "class_encoded_input_stream_3_01_u_t_f8_3_4_00_01_memory_stream_01_4.html", null ],
    [ "EncodedOutputStream< Encoding, OutputByteStream >", "class_encoded_output_stream.html", null ],
    [ "FalseType", null, [
      [ "internal::IsGenericValueImpl< T, Encoding, Allocator >", "structinternal_1_1_is_generic_value_impl.html", null ]
    ] ],
    [ "FileReadStream", "class_file_read_stream.html", null ],
    [ "FileWriteStream", "class_file_write_stream.html", null ],
    [ "GenericArray< Const, ValueT >", "class_generic_array.html", null ],
    [ "GenericDocument< Encoding, Allocator, StackAllocator >", "class_generic_document.html", null ],
    [ "GenericDocument< UTF8<> >", "class_generic_document.html", null ],
    [ "GenericInsituStringStream< Encoding >", "struct_generic_insitu_string_stream.html", null ],
    [ "GenericMember< Encoding, Allocator >", "struct_generic_member.html", null ],
    [ "GenericMemoryBuffer< Allocator >", "struct_generic_memory_buffer.html", null ],
    [ "GenericObject< Const, ValueT >", "class_generic_object.html", null ],
    [ "GenericPointer< ValueType, Allocator >", "class_generic_pointer.html", null ],
    [ "GenericPointer< ValueType, Allocator >::Token", "struct_generic_pointer_1_1_token.html", null ],
    [ "GenericReader< SourceEncoding, TargetEncoding, StackAllocator >", "class_generic_reader.html", null ],
    [ "GenericSchemaDocument< ValueT, Allocator >", "class_generic_schema_document.html", null ],
    [ "GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >", "class_generic_schema_validator.html", null ],
    [ "GenericStringBuffer< Encoding, Allocator >", "class_generic_string_buffer.html", null ],
    [ "GenericStringRef< CharType >", "struct_generic_string_ref.html", null ],
    [ "GenericStringStream< Encoding >", "struct_generic_string_stream.html", null ],
    [ "GenericValue< Encoding, Allocator >", "class_generic_value.html", null ],
    [ "GenericValue< Encoding, Allocator >::ArrayData", "struct_generic_value_1_1_array_data.html", null ],
    [ "GenericValue< Encoding, Allocator >::Data", "union_generic_value_1_1_data.html", null ],
    [ "GenericValue< Encoding, Allocator >::Flag", "struct_generic_value_1_1_flag.html", null ],
    [ "GenericValue< Encoding, Allocator >::Number", "union_generic_value_1_1_number.html", null ],
    [ "GenericValue< Encoding, Allocator >::Number::I", "struct_generic_value_1_1_number_1_1_i.html", null ],
    [ "GenericValue< Encoding, Allocator >::Number::U", "struct_generic_value_1_1_number_1_1_u.html", null ],
    [ "GenericValue< Encoding, Allocator >::ObjectData", "struct_generic_value_1_1_object_data.html", null ],
    [ "GenericValue< Encoding, Allocator >::ShortString", "struct_generic_value_1_1_short_string.html", null ],
    [ "GenericValue< Encoding, Allocator >::String", "struct_generic_value_1_1_string.html", null ],
    [ "GenericValue< EncodingType, AllocatorType >", "class_generic_value.html", null ],
    [ "GenericValue< rapidjson::Encoding, rapidjson::Allocator >", "class_generic_value.html", null ],
    [ "IGenericRemoteSchemaDocumentProvider< SchemaDocumentType >", "class_i_generic_remote_schema_document_provider.html", null ],
    [ "imaxdiv_t", "structimaxdiv__t.html", null ],
    [ "internal::BigInteger", "classinternal_1_1_big_integer.html", null ],
    [ "internal::DiyFp", "structinternal_1_1_diy_fp.html", null ],
    [ "internal::Double", "classinternal_1_1_double.html", null ],
    [ "internal::GenericRegex< Encoding, Allocator >", "classinternal_1_1_generic_regex.html", null ],
    [ "internal::Hasher< Encoding, Allocator >", "classinternal_1_1_hasher.html", null ],
    [ "internal::Hasher< Encoding, Allocator >::Number::U", "unioninternal_1_1_hasher_1_1_number_1_1_u.html", null ],
    [ "internal::ISchemaStateFactory< SchemaType >", "classinternal_1_1_i_schema_state_factory.html", null ],
    [ "internal::ISchemaValidator", "classinternal_1_1_i_schema_validator.html", null ],
    [ "internal::Schema< SchemaDocumentType >", "classinternal_1_1_schema.html", null ],
    [ "internal::SchemaValidationContext< SchemaDocumentType >", "structinternal_1_1_schema_validation_context.html", null ],
    [ "internal::Stack< Allocator >", "classinternal_1_1_stack.html", null ],
    [ "internal::StreamLocalCopy< Stream, int >", "classinternal_1_1_stream_local_copy.html", null ],
    [ "internal::StreamLocalCopy< Stream, 0 >", "classinternal_1_1_stream_local_copy_3_01_stream_00_010_01_4.html", null ],
    [ "internal::StreamLocalCopy< Stream, 1 >", "classinternal_1_1_stream_local_copy_3_01_stream_00_011_01_4.html", null ],
    [ "internal::TokenHelper< Stack, Ch >", "structinternal_1_1_token_helper.html", null ],
    [ "internal::TokenHelper< Stack, char >", "structinternal_1_1_token_helper_3_01_stack_00_01char_01_4.html", null ],
    [ "internal::TypeHelper< ValueType, T >", "structinternal_1_1_type_helper.html", null ],
    [ "internal::TypeHelper< ValueType, bool >", "structinternal_1_1_type_helper_3_01_value_type_00_01bool_01_4.html", null ],
    [ "internal::TypeHelper< ValueType, const typename ValueType::Ch * >", "structinternal_1_1_type_helper_3_01_value_type_00_01const_01typename_01_value_type_1_1_ch_01_5_01_4.html", null ],
    [ "internal::TypeHelper< ValueType, double >", "structinternal_1_1_type_helper_3_01_value_type_00_01double_01_4.html", null ],
    [ "internal::TypeHelper< ValueType, float >", "structinternal_1_1_type_helper_3_01_value_type_00_01float_01_4.html", null ],
    [ "internal::TypeHelper< ValueType, int >", "structinternal_1_1_type_helper_3_01_value_type_00_01int_01_4.html", null ],
    [ "internal::TypeHelper< ValueType, int64_t >", "structinternal_1_1_type_helper_3_01_value_type_00_01int64__t_01_4.html", null ],
    [ "internal::TypeHelper< ValueType, typename ValueType::Array >", "structinternal_1_1_type_helper_3_01_value_type_00_01typename_01_value_type_1_1_array_01_4.html", null ],
    [ "internal::TypeHelper< ValueType, typename ValueType::ConstArray >", "structinternal_1_1_type_helper_3_01_value_type_00_01typename_01_value_type_1_1_const_array_01_4.html", null ],
    [ "internal::TypeHelper< ValueType, typename ValueType::ConstObject >", "structinternal_1_1_type_helper_3_01_value_type_00_01typename_01_value_type_1_1_const_object_01_4.html", null ],
    [ "internal::TypeHelper< ValueType, typename ValueType::Object >", "structinternal_1_1_type_helper_3_01_value_type_00_01typename_01_value_type_1_1_object_01_4.html", null ],
    [ "internal::TypeHelper< ValueType, uint64_t >", "structinternal_1_1_type_helper_3_01_value_type_00_01uint64__t_01_4.html", null ],
    [ "internal::TypeHelper< ValueType, unsigned >", "structinternal_1_1_type_helper_3_01_value_type_00_01unsigned_01_4.html", null ],
    [ "Type", null, [
      [ "internal::IsGenericValueImpl< T, typename Void< typename T::EncodingType >::Type, typename Void< typename T::AllocatorType >::Type >", "structinternal_1_1_is_generic_value_impl_3_01_t_00_01typename_01_void_3_01typename_01_t_1_1_enco3a51e9d8b4986f001b39e1e8edecb66a.html", null ]
    ] ],
    [ "Type", null, [
      [ "internal::IsGenericValue< T >", "structinternal_1_1_is_generic_value.html", null ]
    ] ],
    [ "MemoryPoolAllocator< BaseAllocator >", "class_memory_pool_allocator.html", null ],
    [ "MemoryPoolAllocator<>", "class_memory_pool_allocator.html", null ],
    [ "MemoryStream", "struct_memory_stream.html", null ],
    [ "ParseResult", "struct_parse_result.html", null ],
    [ "pretty_print::array_wrapper_n< T >", "structpretty__print_1_1array__wrapper__n.html", null ],
    [ "pretty_print::bucket_print_wrapper< T >", "structpretty__print_1_1bucket__print__wrapper.html", null ],
    [ "pretty_print::custom_delims< Delims >", "structpretty__print_1_1custom__delims.html", null ],
    [ "pretty_print::custom_delims_base", "structpretty__print_1_1custom__delims__base.html", [
      [ "pretty_print::custom_delims_wrapper< T, Delims >", "structpretty__print_1_1custom__delims__wrapper.html", null ]
    ] ],
    [ "pretty_print::delimiters< T, TChar >", "structpretty__print_1_1delimiters.html", null ],
    [ "pretty_print::delimiters< ::std::multiset< T, TComp, TAllocator >, char >", "structpretty__print_1_1delimiters_3_01_1_1std_1_1multiset_3_01_t_00_01_t_comp_00_01_t_allocator_01_4_00_01char_01_4.html", null ],
    [ "pretty_print::delimiters< ::std::multiset< T, TComp, TAllocator >, wchar_t >", "structpretty__print_1_1delimiters_3_01_1_1std_1_1multiset_3_01_t_00_01_t_comp_00_01_t_allocator_01_4_00_01wchar__t_01_4.html", null ],
    [ "pretty_print::delimiters< ::std::pair< T1, T2 >, wchar_t >", "structpretty__print_1_1delimiters_3_01_1_1std_1_1pair_3_01_t1_00_01_t2_01_4_00_01wchar__t_01_4.html", null ],
    [ "pretty_print::delimiters< ::std::set< T, TComp, TAllocator >, char >", "structpretty__print_1_1delimiters_3_01_1_1std_1_1set_3_01_t_00_01_t_comp_00_01_t_allocator_01_4_00_01char_01_4.html", null ],
    [ "pretty_print::delimiters< ::std::set< T, TComp, TAllocator >, wchar_t >", "structpretty__print_1_1delimiters_3_01_1_1std_1_1set_3_01_t_00_01_t_comp_00_01_t_allocator_01_4_00_01wchar__t_01_4.html", null ],
    [ "pretty_print::delimiters< ::std::tuple< Args... >, wchar_t >", "structpretty__print_1_1delimiters_3_01_1_1std_1_1tuple_3_01_args_8_8_8_01_4_00_01wchar__t_01_4.html", null ],
    [ "pretty_print::delimiters< ::std::unordered_multiset< T, THash, TEqual, TAllocator >, char >", "structpretty__print_1_1delimiters_3_01_1_1std_1_1unordered__multiset_3_01_t_00_01_t_hash_00_01_tb6b29865f821a150cd18b2892926a3b9.html", null ],
    [ "pretty_print::delimiters< ::std::unordered_multiset< T, THash, TEqual, TAllocator >, wchar_t >", "structpretty__print_1_1delimiters_3_01_1_1std_1_1unordered__multiset_3_01_t_00_01_t_hash_00_01_ta96a3f915dbadf947ec868cf6635b320.html", null ],
    [ "pretty_print::delimiters< ::std::unordered_set< T, THash, TEqual, TAllocator >, char >", "structpretty__print_1_1delimiters_3_01_1_1std_1_1unordered__set_3_01_t_00_01_t_hash_00_01_t_equa3a9e52f9481042d4d60af8f675026fc4.html", null ],
    [ "pretty_print::delimiters< ::std::unordered_set< T, THash, TEqual, TAllocator >, wchar_t >", "structpretty__print_1_1delimiters_3_01_1_1std_1_1unordered__set_3_01_t_00_01_t_hash_00_01_t_equac4c603390a29e53c9e588012a0abf58e.html", null ],
    [ "pretty_print::delimiters< std::pair< T1, T2 >, char >", "structpretty__print_1_1delimiters_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_00_01char_01_4.html", null ],
    [ "pretty_print::delimiters< std::tuple< Args... >, char >", "structpretty__print_1_1delimiters_3_01std_1_1tuple_3_01_args_8_8_8_01_4_00_01char_01_4.html", null ],
    [ "pretty_print::delimiters< T, char >", "structpretty__print_1_1delimiters_3_01_t_00_01char_01_4.html", null ],
    [ "pretty_print::delimiters< T, wchar_t >", "structpretty__print_1_1delimiters_3_01_t_00_01wchar__t_01_4.html", null ],
    [ "pretty_print::delimiters_values< TChar >", "structpretty__print_1_1delimiters__values.html", null ],
    [ "pretty_print::detail::sfinae_base", "structpretty__print_1_1detail_1_1sfinae__base.html", [
      [ "pretty_print::detail::has_begin_end< T >", "structpretty__print_1_1detail_1_1has__begin__end.html", null ],
      [ "pretty_print::detail::has_const_iterator< T >", "structpretty__print_1_1detail_1_1has__const__iterator.html", null ]
    ] ],
    [ "pretty_print::print_container_helper< T, TChar, TCharTraits, TDelimiters >", "structpretty__print_1_1print__container__helper.html", null ],
    [ "pretty_print::print_container_helper< T, TChar, TCharTraits, TDelimiters >::printer< U >", "structpretty__print_1_1print__container__helper_1_1printer.html", null ],
    [ "pretty_print::print_container_helper< T, TChar, TCharTraits, TDelimiters >::printer< std::pair< T1, T2 > >", "structpretty__print_1_1print__container__helper_1_1printer_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
    [ "pretty_print::print_container_helper< T, TChar, TCharTraits, TDelimiters >::printer< std::tuple< Args... > >", "structpretty__print_1_1print__container__helper_1_1printer_3_01std_1_1tuple_3_01_args_8_8_8_01_4_01_4.html", null ],
    [ "pretty_print::print_container_helper< T, TChar, TCharTraits, TDelimiters >::printer< std::tuple< Args... > >::Int< I >", "structpretty__print_1_1print__container__helper_1_1printer_3_01std_1_1tuple_3_01_args_8_8_8_01_4_01_4_1_1_int.html", null ],
    [ "PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >", "class_pretty_writer.html", null ],
    [ "rapidcsv::Converter< T >", "classrapidcsv_1_1_converter.html", null ],
    [ "rapidcsv::ConverterParams", "structrapidcsv_1_1_converter_params.html", null ],
    [ "rapidcsv::Document", "classrapidcsv_1_1_document.html", null ],
    [ "rapidcsv::LabelParams", "structrapidcsv_1_1_label_params.html", null ],
    [ "rapidcsv::LineReaderParams", "structrapidcsv_1_1_line_reader_params.html", null ],
    [ "rapidcsv::SeparatorParams", "structrapidcsv_1_1_separator_params.html", null ],
    [ "Allocator", "classrapidjson_1_1_allocator.html", null ],
    [ "Encoding", "classrapidjson_1_1_encoding.html", null ],
    [ "Handler", "classrapidjson_1_1_handler.html", null ],
    [ "Stream", "classrapidjson_1_1_stream.html", null ],
    [ "rapidxml::attribute_iterator< Ch >", "classrapidxml_1_1attribute__iterator.html", null ],
    [ "rapidxml::file< Ch >", "classrapidxml_1_1file.html", null ],
    [ "rapidxml::memory_pool< Ch >", "classrapidxml_1_1memory__pool.html", null ],
    [ "rapidxml::node_iterator< Ch >", "classrapidxml_1_1node__iterator.html", null ],
    [ "rapidxml::xml_attribute< Ch >", "classrapidxml_1_1xml__attribute.html", null ],
    [ "rapidxml::xml_base< Ch >", "classrapidxml_1_1xml__base.html", null ],
    [ "rapidxml::xml_document< Ch >", "classrapidxml_1_1xml__document.html", null ],
    [ "rapidxml::xml_node< Ch >", "classrapidxml_1_1xml__node.html", null ],
    [ "RQuantity< MassDim, LengthDim, TimeDim, AngleDim, CurrentDim, LumDim, SubDim, TempDim >", "class_r_quantity.html", null ],
    [ "SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >", "class_schema_validating_reader.html", null ],
    [ "internal::Stack< CrtAllocator >", "classinternal_1_1_stack.html", null ],
    [ "internal::Stack< rapidjson::Allocator >", "classinternal_1_1_stack.html", null ],
    [ "internal::Stack< rapidjson::CrtAllocator >", "classinternal_1_1_stack.html", null ],
    [ "internal::Stack< StackAllocator >", "classinternal_1_1_stack.html", null ],
    [ "std::exception", null, [
      [ "rapidcsv::no_converter", "classrapidcsv_1_1no__converter.html", null ],
      [ "std::runtime_error", null, [
        [ "rapidxml::parse_error", "classrapidxml_1_1parse__error.html", [
          [ "rapidxml::eof_error", "classrapidxml_1_1eof__error.html", null ]
        ] ],
        [ "rapidxml::validation_error", "classrapidxml_1_1validation__error.html", null ]
      ] ]
    ] ],
    [ "false_type", null, [
      [ "pretty_print::is_container< char[N]>", "structpretty__print_1_1is__container_3_01char_0f_n_0e_4.html", null ]
    ] ],
    [ "integral_constant", null, [
      [ "pretty_print::is_container< T >", "structpretty__print_1_1is__container.html", null ]
    ] ],
    [ "iterator", null, [
      [ "GenericMemberIterator< Const, Encoding, Allocator >", "class_generic_member_iterator.html", null ]
    ] ],
    [ "true_type", null, [
      [ "pretty_print::is_container< std::pair< T1, T2 > >", "structpretty__print_1_1is__container_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
      [ "pretty_print::is_container< std::tuple< Args... > >", "structpretty__print_1_1is__container_3_01std_1_1tuple_3_01_args_8_8_8_01_4_01_4.html", null ],
      [ "pretty_print::is_container< std::valarray< T > >", "structpretty__print_1_1is__container_3_01std_1_1valarray_3_01_t_01_4_01_4.html", null ],
      [ "pretty_print::is_container< T[N]>", "structpretty__print_1_1is__container_3_01_t_0f_n_0e_4.html", null ]
    ] ],
    [ "StreamTraits< Stream >", "struct_stream_traits.html", null ],
    [ "StreamTraits< GenericInsituStringStream< Encoding > >", "struct_stream_traits_3_01_generic_insitu_string_stream_3_01_encoding_01_4_01_4.html", null ],
    [ "StreamTraits< GenericStringStream< Encoding > >", "struct_stream_traits_3_01_generic_string_stream_3_01_encoding_01_4_01_4.html", null ],
    [ "Transcoder< SourceEncoding, TargetEncoding >", "struct_transcoder.html", null ],
    [ "Transcoder< Encoding, Encoding >", "struct_transcoder_3_01_encoding_00_01_encoding_01_4.html", null ],
    [ "UTF16< CharType >", "struct_u_t_f16.html", null ],
    [ "UTF16< wchar_t >", "struct_u_t_f16.html", [
      [ "UTF16BE< CharType >", "struct_u_t_f16_b_e.html", null ],
      [ "UTF16LE< CharType >", "struct_u_t_f16_l_e.html", null ]
    ] ],
    [ "UTF32< CharType >", "struct_u_t_f32.html", null ],
    [ "UTF32< unsigned >", "struct_u_t_f32.html", [
      [ "UTF32BE< CharType >", "struct_u_t_f32_b_e.html", null ],
      [ "UTF32LE< CharType >", "struct_u_t_f32_l_e.html", null ]
    ] ],
    [ "UTF8< CharType >", "struct_u_t_f8.html", null ],
    [ "votable::Field", "structvotable_1_1_field.html", null ],
    [ "votable::Param", "structvotable_1_1_param.html", null ],
    [ "votable::VOField< T >", "structvotable_1_1_v_o_field.html", null ],
    [ "votable::VOTable", "classvotable_1_1_v_o_table.html", null ],
    [ "Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >", "class_writer.html", null ],
    [ "Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Level", "struct_writer_1_1_level.html", null ],
    [ "rapidxml::xml_attribute< char >", "classrapidxml_1_1xml__attribute.html", null ],
    [ "rapidxml::xml_node< char >", "classrapidxml_1_1xml__node.html", null ]
];